services:
  - type: worker
    name: family-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: TARGET_CHANNEL_ID
        sync: false
      - key: RECRUIT_BOARD_CHANNEL_ID
        sync: false
      - key: INVITE_CHANNEL_ID
        sync: false
      - key: RECRUIT_REPORT_CHANNEL_ID
        sync: false
      - key: BIRTHDAY_BOARD_CHANNEL_ID
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
      - key: WELCOME_CHANNEL_ID
        sync: false
      - key: AUTOMOD_CHANNEL_ID
        sync: false
      - key: APP_CREATE_CHANNEL_ID
        sync: false
      - key: APP_LOG_CHANNEL_ID
        sync: false
      - key: APP_CATEGORY_ID
        sync: false
      - key: RECRUIT_APP_BANNER_CHANNEL_ID
        sync: false
      - key: RECRUIT_APP_LIST_CHANNEL_ID
        sync: false
      - key: ADMIN_PANEL_CHANNEL_ID
        sync: false
      - key: MEETING_ROLE_ID
        sync: false
      - key: MEETING_VOICE_CHANNEL_ID
        sync: false
